Install java 11 on the AMIs.
gocd/gocd-cloud pull request #12
Opened 2018-12-15 01:26 UTC by varshavaradarajan

@bdpiparva - I haven't verified by building the AMI. Let me know if this is alright. I'll do the same for the demo AMI.

2018-12-15 03:12 UTC, bdpiparva commented
Changes looks good to me. However, for centos 7 openjdk 11 is now avay through yum.

2018-12-15 03:14 UTC, bdpiprava requested changes

2018-12-15 03:14 UTC, bdpiparva commented on go-server-packer.json
>          "sudo yum install -y java-1.8.0-openjdk-headless git mercurial subversion openssh-clients bash wget",
Do remove jdk 1.8.

2019-03-18 05:37 UTC, varshavaradarajan commented
> for centos 7 openjdk 11 is now avay through yum.

Not available on amazon linux, @bdpiparva . Did `yum list --showduplicates java*`. Showed only java 7 & 8.

2019-03-23 01:31 UTC, bdpiparva commented on go-server-demo-packer.json
> +    "openjdk_url": "https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz",
Need to update openjdk url to `https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz`

2019-03-23 01:32 UTC, bdpiprava approved these changes

2019-03-23 04:36 UTC, merged